version: "3.1"

services: 

  wordpress:
    image:  wordpress:php7.2-apache
    ports: 
      - 8085:80
    environment:
      WORDPRESS_DB_HOST: mysqldb:3306
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_NAME: wordpress
    links: 
      - mysqldb:mysqldb
    depends_on: 
      - mysqldb

  mysqldb:
    image: mysql:8.0.13
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABSE: wordpress
    volumes: 
      - ~/docker/mysql-data:/var/lib/mysql